export default [
  {
    id: 1,
    title: 'Capstone - Module 1',
    description: 'the description',
    author: 'Mostafa Ahangarha',
    ghUsername: 'ahangarha',
    repo: 'https://github.com/ahangarha/sfd2022-sample-design/',
    license: 'AGPL',
    screenshot:
      'https://github.com/ahangarha/SFD2022-sample-design/raw/main/screenshot.png',
    publishedOn: '2022-02-03',
    techs: ['HTML/CSS'],
    module: 1,
  },
  {
    id: 2,
    title: 'Module 1 capstone project - Creative Anime Convention website',
    description:
      'This website is for an anime convention it has two pages a home page and about page, the home page contains information about the convention (events, guests and sponsors) and the about page contains information about the ones holding the anime convention.',
    author: 'Ammar Hamlaoui',
    ghUsername: 'mirouhml',
    repo: 'https://github.com/mirouhml/anime-convention-project',
    license: 'MIT',
    screenshot:
      'https://github.com/mirouhml/anime-convention-project/raw/main/src/screenshot.png',
    publishedOn: '2022-02-01',
    techs: ['HTML/CSS'],
    module: 1,
  },
  {
    id: 3,
    title: 'Module 1 capstone project - Talanta Mtaani',
    description:
      'The project is about a music competition that aims to help the underprevileged young people to showcase their talents. With the hope that they will get a platform to sign deals and start producing professional music.',
    author: 'Nemwel Boniface',
    ghUsername: 'Nemwel-Boniface',
    repo: 'https://github.com/Nemwel-Boniface/Talanta-Mtaani',
    license: 'MIT',
    screenshot:
      'https://github.com/Nemwel-Boniface/Talanta-Mtaani/raw/main/images/TalantaM-DV.png',
    publishedOn: '2022-02-02',
    techs: ['HTML/CSS'],
    module: 1,
  },
  {
    id: 4,
    title: 'HTML/CSS capstone project - Marock music festival',
    description:
      "This project was built with a Mobile-first design perspective and it's mobile responsive. for the design, the main technologies in CSS are flexbox and media query. The Festival was inspired by the Boulevard urban music festival in Morocco.",
    author: 'Ismail Courr',
    ghUsername: 'ismailco',
    repo: 'https://github.com/Ismailco/First-capstone-project_Conference-page',
    license: 'GPL-3.0',
    screenshot: 'https://ismailcourr.ml/img/projects/marock/preview1.png',
    publishedOn: '2022-02-04',
    techs: ['HTML/CSS'],
    module: 1,
  },
  {
    id: 5,
    title: 'Module 1 Capstone project - Tech Events',
    description: 'This project is a website for tech events.',
    author: 'Cedric KOSSI',
    ghUsername: 'kosher9',
    repo: 'https://github.com/kosher9/tech_event',
    license: 'MIT',
    screenshot: 'https://github.com/kosher9/tech_event/raw/master/images/preview.png',
    publishedOn: '2022-02-09',
    techs: ['HTML/CSS', 'JavaScript'],
    module: 1,
  },
  {
    id: 6,
    title: 'CovidWatch',
    description: 'A web application to check latest daily statistics of new Covid-19 confirmed cases',
    author: 'Mostafa Ahangarha',
    ghUsername: 'ahangarha',
    repo: 'https://github.com/ahangarha/CovidWatch/',
    license: 'AGPL',
    screenshot:
      'https://github.com/ahangarha/CovidWatch/raw/develop/screenshot.png',
    publishedOn: '2022-04-15',
    techs: ['HTML/CSS', 'React', 'Redux', 'Tailwindcss'],
    module: 3,
  },
  {
    id: 7,
    title: 'Math Magicians',
    description: 'Math Magicians is a Single Page Application (SPA) created in React that allows users to make simple calculations & Read some famous Quotes.',
    author: 'Awais Amjed',
    ghUsername: 'awais-amjed',
    repo: 'https://github.com/awais-amjed/math-magicians',
    license: 'MIT',
    screenshot:
      'https://raw.githubusercontent.com/awais-amjed/math-magicians/development/app_screenshot.png',
    publishedOn: '2022-04-11',
    techs: ['HTML/CSS', 'React', 'Scss'],
    module: 3,
  },
  {
    id: 8,
    title: 'Giggy',
    description: 'This is a Web Application with some jokes related to coding & Dark Humor. Created with data from the JokeAPI.',
    author: 'Awais Amjed',
    ghUsername: 'awais-amjed',
    repo: 'https://github.com/awais-amjed/giggy',
    license: 'MIT',
    screenshot:
      'https://github.com/awais-amjed/giggy/raw/dev/home_page_screenshot.png',
    publishedOn: '2022-03-12',
    techs: ['HTML/CSS', 'React'],
    module: 3,
  },
  {
    id: 9,
    title: 'To Do List',
    description: 'Keep a track of all the tasks you need to do and Check off ones you have completed - Created using HTML, SCSS, JavaScript and Webpack.',
    author: 'Awais Amjed',
    ghUsername: 'awais-amjed',
    repo: 'https://github.com/awais-amjed/to-do-list',
    license: '-',
    screenshot:
      'https://github.com/awais-amjed/to-do-list/raw/master/app_screenshot.png',
    publishedOn: '2022-02-23',
    techs: ['HTML/CSS', 'JavaScript', 'Scss'],
    module: 2,
  },
  {
    id: 10,
    title: 'Taste Jamaica',
    description: 'See a list of Jamaican meals, like them, or leave comments for each. ',
    author: 'Mostafa Ahangarha, David Ouma',
    ghUsername: 'ahangarha',
    repo: 'https://github.com/ahangarha/JavaScript-Capstone/',
    license: 'MIT',
    screenshot:
      'https://github.com/ahangarha/JavaScript-Capstone/raw/develop/screenshot.png',
    publishedOn: '2022-03-27',
    techs: ['HTML/CSS', 'JavaScript', 'Jest'],
    module: 2,
  },
  {
    id: 11,
    title: 'Math Magicians',
    description: ' An educational project for making a calculator with Reactjs.',
    author: 'Mostafa Ahangarha',
    ghUsername: 'ahangarha',
    repo: 'https://github.com/ahangarha/MV-MathMagicians/',
    license: 'AGPL',
    screenshot:
      'https://github.com/ahangarha/MV-MathMagicians/raw/develop/screenshot.png',
    publishedOn: '2022-03-25',
    techs: ['HTML/CSS', 'React', 'Jest'],
    module: 3,
  },
];
