export default [
  {
    id: 1,
    title: 'Capstone - Module 1',
    description: 'the description',
    author: 'Mostafa Ahangarha',
    ghUsername: 'ahangarha',
    repo: 'https://github.com/ahangarha/sfd2022-sample-design/',
    license: 'AGPL',
    screenshot:
      'https://github.com/ahangarha/SFD2022-sample-design/raw/main/screenshot.png',
    publishedOn: '2022-02-03',
    techs: ['HTML/CSS'],
    module: 1,
  },
  {
    id: 2,
    title: 'Module 1 capstone project - Creative Anime Convention website',
    description:
      'This website is for an anime convention it has two pages a home page and about page, the home page contains information about the convention (events, guests and sponsors) and the about page contains information about the ones holding the anime convention.',
    author: 'Ammar Hamlaoui',
    ghUsername: 'mirouhml',
    repo: 'https://github.com/mirouhml/anime-convention-project',
    license: 'MIT',
    screenshot:
      'https://github.com/mirouhml/anime-convention-project/raw/main/src/screenshot.png',
    publishedOn: '2022-02-01',
    techs: ['HTML/CSS'],
    module: 1,
  },
  {
    id: 3,
    title: 'Module 1 capstone project - Talanta Mtaani',
    description:
      'The project is about a music competition that aims to help the underprevileged young people to showcase their talents. With the hope that they will get a platform to sign deals and start producing professional music.',
    author: 'Nemwel Boniface',
    ghUsername: 'Nemwel-Boniface',
    repo: 'https://github.com/Nemwel-Boniface/Talanta-Mtaani',
    license: 'MIT',
    screenshot:
      'https://github.com/Nemwel-Boniface/Talanta-Mtaani/raw/main/images/TalantaM-DV.png',
    publishedOn: '2022-02-02',
    techs: ['HTML/CSS'],
    module: 1,
  },
  {
    id: 4,
    title: 'HTML/CSS capstone project - Marock music festival',
    description:
      "This project was built with a Mobile-first design perspective and it's mobile responsive. for the design, the main technologies in CSS are flexbox and media query. The Festival was inspired by the Boulevard urban music festival in Morocco.",
    author: 'Ismail Courr',
    ghUsername: 'ismailco',
    repo: 'https://github.com/Ismailco/First-capstone-project_Conference-page',
    license: 'GPL-3.0',
    screenshot: 'https://ismailcourr.ml/img/projects/marock/preview1.png',
    publishedOn: '2022-02-04',
    techs: ['HTML/CSS'],
    module: 1,
  },
  {
    id: 5,
    title: 'Module 1 Capstone project - Tech Events',
    description: 'This project is a website for tech events.',
    author: 'Cedric KOSSI',
    ghUsername: 'kosher9',
    repo: 'https://github.com/kosher9/tech_event',
    license: 'MIT',
    screenshot: 'https://github.com/kosher9/tech_event/raw/master/images/preview.png',
    publishedOn: '2022-02-09',
    techs: ['HTML/CSS', 'JavaScript'],
    module: 1,
  },
  {
    id: 6,
    title: 'CovidWatch',
    description: 'A web application to check latest daily statistics of new Covid-19 confirmed cases',
    author: 'Mostafa Ahangarha',
    ghUsername: 'ahangarha',
    repo: 'https://github.com/ahangarha/CovidWatch/',
    license: 'AGPL',
    screenshot:
      'https://github.com/ahangarha/CovidWatch/raw/develop/screenshot.png',
    publishedOn: '2022-04-15',
    techs: ['HTML/CSS', 'React', 'Redux', 'Tailwindcss'],
    module: 3,
  },
  {
    id: 7,
    title: 'Math Magicians',
    description: 'Math Magicians is a Single Page Application (SPA) created in React that allows users to make simple calculations & Read some famous Quotes.',
    author: 'Awais Amjed',
    ghUsername: 'awais-amjed',
    repo: 'https://github.com/awais-amjed/math-magicians',
    license: 'MIT',
    screenshot:
      'https://raw.githubusercontent.com/awais-amjed/math-magicians/development/app_screenshot.png',
    publishedOn: '2022-04-11',
    techs: ['HTML/CSS', 'React', 'Scss'],
    module: 3,
  },
  {
    id: 8,
    title: 'Giggy',
    description: 'This is a Web Application with some jokes related to coding & Dark Humor. Created with data from the JokeAPI.',
    author: 'Awais Amjed,  Akumu Bavon',
    ghUsername: 'awais-amjed',
    repo: 'https://github.com/awais-amjed/giggy',
    license: 'MIT',
    screenshot:
      'https://github.com/awais-amjed/giggy/raw/dev/home_page_screenshot.png',
    publishedOn: '2022-03-12',
    techs: ['HTML/CSS', 'React'],
    module: 3,
  },
  {
    id: 9,
    title: 'To Do List',
    description: 'Keep a track of all the tasks you need to do and Check off ones you have completed - Created using HTML, SCSS, JavaScript and Webpack.',
    author: 'Awais Amjed',
    ghUsername: 'awais-amjed',
    repo: 'https://github.com/awais-amjed/to-do-list',
    license: '-',
    screenshot:
      'https://github.com/awais-amjed/to-do-list/raw/master/app_screenshot.png',
    publishedOn: '2022-02-23',
    techs: ['HTML/CSS', 'JavaScript', 'Scss'],
    module: 2,
  },
  {
    id: 10,
    title: 'Taste Jamaica',
    description: 'See a list of Jamaican meals, like them, or leave comments for each. ',
    author: 'Mostafa Ahangarha, David Ouma',
    ghUsername: 'ahangarha',
    repo: 'https://github.com/ahangarha/JavaScript-Capstone/',
    license: 'MIT',
    screenshot:
      'https://github.com/ahangarha/JavaScript-Capstone/raw/develop/screenshot.png',
    publishedOn: '2022-03-27',
    techs: ['HTML/CSS', 'JavaScript', 'Jest'],
    module: 2,
  },
  {
    id: 11,
    title: 'Math Magicians',
    description: 'An educational project for making a calculator with Reactjs.',
    author: 'Mostafa Ahangarha',
    ghUsername: 'ahangarha',
    repo: 'https://github.com/ahangarha/MV-MathMagicians/',
    license: 'AGPL',
    screenshot:
      'https://github.com/ahangarha/MV-MathMagicians/raw/develop/screenshot.png',
    publishedOn: '2022-03-25',
    techs: ['HTML/CSS', 'React', 'Jest'],
    module: 3,
  },
  {
    id: 11,
    title: 'Todolist (js)',
    description: 'A simple ToDo list project made by JavaScript. One can add, edit and remove todos as well as marking them as completed.',
    author: 'Mostafa Ahangarha',
    ghUsername: 'ahangarha',
    repo: 'https://github.com/ahangarha/MV-ToDo-List',
    license: 'AGPL',
    screenshot:
      'https://github.com/ahangarha/MV-ToDo-List/raw/main/screenshot.png',
    publishedOn: '2022-03-18',
    techs: ['HTML/CSS', 'JavaScript'],
    module: 2,
  },
  {
    id: 12,
    title: 'Covid-19 Tracker',
    description: 'This is a website that shows recent and old data of Covid-19 stats for all the countries of the world, it uses this API as the data source.',
    author: 'Ammar Hamlaoui',
    ghUsername: 'mirouhml',
    repo: 'https://github.com/mirouhml/covid-19-tracker',
    license: 'MIT',
    screenshot:
      'https://user-images.githubusercontent.com/20567503/163427412-b95568c1-fc81-47e6-91d4-392432f5a425.png',
    publishedOn: '2022-04-14',
    techs: ['HTML/CSS', 'React', 'Redux'],
    module: 3,
  },
  {
    id: 13,
    title: 'Math Magicians',
    description: 'This is Math Magicians website, it has a calculator and some quotes about maths.',
    author: 'Ammar Hamlaoui',
    ghUsername: 'mirouhml',
    repo: 'https://github.com/mirouhml/math-magicians',
    license: 'MIT',
    screenshot:
      'https://user-images.githubusercontent.com/20567503/159556805-5e59baaf-171f-4f46-983f-a85bf3abc1ee.png',
    publishedOn: '2022-03-23',
    techs: ['HTML/CSS', 'React'],
    module: 3,
  },
  {
    id: 14,
    title: 'To-Do-List',
    description: 'This is a website for a simple to do list, where you can add and remove tasks, edit and reorder them as you see fit.',
    author: 'Ammar Hamlaoui',
    ghUsername: 'mirouhml',
    repo: 'https://github.com/mirouhml/To-Do-list',
    license: 'MIT',
    screenshot:
      'https://github.com/mirouhml/To-Do-list/raw/main/src/asset/screenshot.png',
    publishedOn: '2022-02-24',
    techs: ['HTML/CSS', 'JavaScript'],
    module: 2,
  },
  {
    id: 15,
    title: 'ToDo-List',
    description: 'This is a website A web app that helps you keep track of your most important tasks. You can add, delete, edits tasks as you wish, and they always stay on your browser.',
    author: 'Sodiq Aderibigbe',
    ghUsername: 'deyemiobaa',
    repo: 'https://github.com/deyemiobaa/ToDo-List',
    license: 'MIT',
    screenshot:
      'https://raw.githubusercontent.com/deyemiobaa/ToDo-List/main/src/images/app-sc.png',
    publishedOn: '2022-04-21',
    techs: ['HTML/CSS', 'JavaScript', 'Webpack'],
    module: 2,
  },
  {
    id: 16,
    title: 'ShowBox Movies',
    description: 'Search for info about your favorite movies and tv shows on the ShowBox Movie Database',
    author: 'Sodiq Aderibigbe, Sentayhu berhanu',
    ghUsername: 'deyemiobaa',
    repo: 'https://github.com/deyemiobaa/Movie-Database',
    license: 'MIT',
    screenshot:
      'https://raw.githubusercontent.com/deyemiobaa/Movie-Database/dev/src/app-sc.png',
    publishedOn: '2022-04-21',
    techs: ['HTML/CSS', 'JavaScript', 'Webpack', 'API'],
    module: 2,
  },
];
